"""initial migration

Revision ID: 180c6fcd474d
Revises: 17b8aa2c8569
Create Date: 2016-05-17 22:40:36.688638

"""

# revision identifiers, used by Alembic.
revision = '180c6fcd474d'
down_revision = '17b8aa2c8569'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
